on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js v18.14.1
      uses: actions/setup-node@v4
      with:
          node-version: v18.14.1
    - name: Install Dependencies
      run: npm install
    - name: Build Project
      run: npm run build
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env: 
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        VITE_API_BASE_URI: ${{ secrets.VITE_API_BASE_URI}}
        AWS_REGION: 'eu-west-3' # optional: defaults to us-east-1
        SOURCE_DIR: 'dist'